### ISSUE TITLE
Cannot create multi-day all-day events

### ISSUE THREAD

**Issue by glynternet** [scientific-python/yaml2ics#108]
It would be great to be able to create multi-day all-day events.

The following yaml
```yaml
events:
  - summary: Single-day all-day event
    begin: 2025-01-01
  - summary: Multi-day all-day event (Jan 1st and 2nd)
    begin: 2025-01-01
    end: 2025-01-03
```

creates
```ical
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py 0.8.0-dev0 - http://git.io/lLljaA
BEGIN:VEVENT
DTSTART;VALUE=DATE:20250101
DTEND;VALUE=DATE:20250102
SUMMARY:Single-day all-day event
UID:13e9dc7f-0cb1-453c-bcc3-cadd08aab1eb@13e9.org
DTSTAMP:20250106T012847Z
END:VEVENT
BEGIN:VEVENT
DTSTART:20250101T000000
DTEND:20250103T000000
SUMMARY:Multi-day all-day event (Jan 1st and 2nd)
UID:ce9f8683-7f2e-4de4-8fcc-1aa3e41a0469@ce9f.org
DTSTAMP:20250106T012847Z
END:VEVENT
END:VCALENDAR
```

When I created a multi-day all-day event in google calendar and exported it, the fields were
```ical
DTSTART;VALUE=DATE:20250101
DTEND;VALUE=DATE:20250103
```

It looks like we'd need a change to the code around here to hand when both `begin` and `end` are both dates rather than timestamps, or something like that?
https://github.com/scientific-python/yaml2ics/blob/1da44eb942ebd9aaa5e73b89eafff97b2d9c137d/yaml2ics.py#L79-L81
