### ISSUE TITLE
Intervals between events is not respected

### ISSUE THREAD

**Issue by melissawm** [scientific-python/yaml2ics#14]
When creating repeated events, the `interval` field is not respected.

For example:

```
events:
  - summary: My meeting
    description: |
      Coffee and biscuits.
    begin: 2022-01-19 18:00:00
    end: 2022-01-19 19:00:00
    repeat:
      interval:
        days: 14
      until: 2025-01-01 00:00:00
```

Generates the following `ics` calendar:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:ics.py 0.8.0-dev - http://git.io/lLljaA
BEGIN:VEVENT
DTSTART:20220119T180000
DTEND:20220119T190000
SUMMARY:My meeting
UID:8b4a8f27-2231-48c9-82cd-d170a6f90f7e@8b4a.org
DESCRIPTION:Coffee and biscuits.
DTSTAMP:20220212T001023Z
RRULE:FREQ=DAILY;UNTIL=20250101T000000
END:VEVENT
END:VCALENDAR
```

Note the `FREQ=DAILY`. Importing this into google calendar results in the following

<img width="1073" alt="Screen Shot 2022-02-11 at 9 12 43 PM" src="https://user-images.githubusercontent.com/3949932/153687232-4f4d8187-8a14-442a-b583-21458676ef8f.png">
