### ISSUE TITLE
Exceptions must include time

### ISSUE THREAD

**Issue by mikael-s** [scientific-python/yaml2ics#51]
Hello,

Thanks for the project!

I gave a try to `yaml2ics` as I'm planning to use a yaml file in order to manage some of my agendas.
I made the following example, where a recurring event has some exceptions:
```yaml
name: Test
timezone: Europe/Paris

events:
  - summary: Event1
    begin: 2023-03-10 09:00:00
    duration:
      minutes: 195
    location: M3
    repeat:
      interval:
        weeks: 1
      until: 2023-05-05
      except_on:
        - 2023-03-17
        - 2023-03-31
        - 2023-04-21
        - 2023-04-28
```

With `yaml2ICS.py`, the produced ICS has the following line for the exceptions: `EXDATE;TZID=/ics.py/2020.1/Europe/Paris:20230317,20230331,20230421,20230428`. It looks like this is ignored by the software I used for importing my ICS (ie. Zimbra Calendar, Nextcloud Calendar, Google Calendar) as the exceptions were not taken into account.

However adding the time to the exceptions (either in the YAML or in the ICS) solve the issue. Would it be possible to automatically add the same time as the start time if no time was specified by the user?

Thanks!
