### ISSUE TITLE
`except_on` and `also_on` seem to not be working as intended

### ISSUE THREAD

**Issue by stefanv** [scientific-python/yaml2ics#54]
The test calendar makes use of this feature and compiles, so I'm not sure what's up yet.

Here's the failing calendar:

```
name: scikit-image Community Calendar
events:
  - summary: scikit-image Community Call (Europe/Africa)
    description: |
      The scikit-image Community Call. Timezone-friendly for Europe/Africa.

      Meeting notes: https://hackmd.io/@scientific-python/HJWUBDVNi
      Archive: https://github.com/scikit-image/meeting-notes
    begin: 2022-09-13 17:00:00 +00:00
    end: 2022-09-13 18:00:00 +00:00
    url: https://us06web.zoom.us/j/88060567580?pwd=THRpaWFnSFNwK0Fycy9FVk5RYnV5UT09
    repeat:
      interval:
        days: 14
      until: 2025-01-01 00:00:00 +00:00
  - summary: scikit-image Community Call (Americas/Oceania)
    description: |
      The scikit-image Community Call. Timezone-friendly for Americas/Oceania.

      Meeting notes: https://hackmd.io/@scientific-python/HJWUBDVNi
      Archive: https://github.com/scikit-image/meeting-notes
    begin: 2022-09-20 23:00:00 +00:00
    end: 2022-09-21 00:00:00 +00:00
    url: https://us06web.zoom.us/j/88060567580?pwd=THRpaWFnSFNwK0Fycy9FVk5RYnV5UT09
    repeat:
      interval:
        days: 14
      until: 2025-01-01 00:00:00 +00:00
      except_on:
        - 2023-05-30
      also_on:
        - 2023-05-31
```
